import numpy as np
from typing import Dict, Any

class SegyFile:
    def __init__(self, path: str) -> None: ...
    def get_trace(self, trace_number: int) -> np.ndarray: ...
    def get_trace_range(self, start: int, end: int) -> np.ndarray: ...
    def get_metadata(self) -> Dict[str, Any]: ...
    def get_header(self) -> str: ...